### PR TITLE
Develop nodes reroute

### PR DESCRIPTION
**Pull request by SergioPerez32**
Rerouted front end nodes to get data from backend through the api gateway (using port 8000 instead of 3000) and added the necessary routes in the kong.yml for said change

### CODE REVIEW

**Review by Ronald803 — APPROVED** [review]
Sorry I got confused, with kong you are replacing "8000" instead of "3000/api/diagram/icons" in the endpoint ?

**Comment by SergioPerez32** [comment]
> Sorry I got confused, with kong you are replacing "8000" instead of "3000/api/diagram/icons" in the endpoint right?

Yes, that's the change exactly Ronald

**Review by AnaMartinez755 — APPROVED** [review]
Looks good !!

**Comment by AnaMartinez755** [comment]
@Ronald803 we should update front in vercel to 8000/nodes

**Comment by Ronald803** [comment]
@AnaMartinez755 these changes has been deployed to vercel, please check if everything works well

**Pull request merged**
